server:
  port: 8888
  servlet:
    context-path: /student

spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522/XEPDB1
    username: quangnv3
    password: quang1998
    hikari:
      allow-pool-suspension: false
      auto-commit: false
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 300000
      max-lifetime: 180000
      idle-timeout: 30000
      pool-name: hikari-pool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
app:
  jwt:
    secret: KYIVtA7915PUEWTqTca74sENpw48u7nkzSJiJmitF7D2PJWOu
    expriedTime: 6000000

