
server:
  port: 8080

rabbitMQ:
  host: 10.22.7.88
  port: 6789
  username: qrcode
  password: qrcode
  exchange-type: topic
  virtual-host: qrcode
  request-heart-beat: 45
  topic-exchange-name: exchange-one
  queue-name: tien.test.qrcode.2
  routing-key: routing.*
  routing-key-one: routing.one
  channel:
    max-total: 30
    max-idle: 25
    min-idle: 20
    max-wait: 120000
    time-between-eviction-runs: 10

redis:
  password: testredis@123
  database: 0
  connection-timeout: 60000
  port: 26379
  lettuce:
    pool:
      max-total: 30
      max-idle: 25
      min-idle: 20
      max-wait: 60000
      time-between-evict-run: 10
  sentinel:
    master: redismaster
    nodes: >
      10.22.7.111,
      10.22.7.112

database:
  driver-class-name: oracle.jdbc.OracleDriver
  host: 10.22.7.63
  post: 1521
  url: jdbc:oracle:thin:@10.22.7.63:1521/GTGTTEST
  username: mms
  password: mms
  sid: GTGTTEST
  pool:
    name: hikariPoolTest
    maximun-pool-size: 2
    allow-pool-suspension: false
    minimun-idle: 1
    idle-timeout: 30000
    connection-timeout: 30000
    max-life-time: 180000
    auto-commit: false
  cache-prep-stmts: true
  prep-stmt-cache-size: 250
  prep-stmt-cache-sql-limit: 2048
  use-server-prep-stmts: true



